const ACTION_TYPES = {
  ADD_WARRIORS: 'ADD_WARRIORS',
  ADD_WARRIOR: 'ADD_WARRIOR',
  DELETE_WARRIOR: 'DELETE_WARRIOR',
  ADD_WARRIOR_TO_LIST: 'ADD_WARRIOR_TO_LIST',
};

export default ACTION_TYPES;
